import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AuthInfo, ConnectionProfile, PairedDevice } from '../types';
import { Theme } from '../theme';
import { authenticatedHeaders, formatRelative, normalizeAgentURL } from '../utils';
import { ActionButton, Icon, InfoBanner, ScreenHeading } from './ui';

export function DevicesScreen({profile,authInfo,theme,onBack,onPair,onSelfRevoked}:{profile:ConnectionProfile;authInfo:AuthInfo|null;theme:Theme;onBack:()=>void;onPair:()=>void;onSelfRevoked:()=>Promise<void>}){
  const [devices,setDevices]=useState<PairedDevice[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [revoking,setRevoking]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch(normalizeAgentURL(profile,'/devices'),{headers:authenticatedHeaders(profile)});if(!response.ok)throw new Error();setDevices(await response.json() as PairedDevice[])}catch{setError('Não foi possível consultar os dispositivos.')}finally{setLoading(false)}},[profile]);
  useEffect(()=>{void load()},[load]);
  const revoke=(device:PairedDevice)=>Alert.alert(device.id===authInfo?.credentialId?'Desconectar este iPhone?':'Revogar dispositivo',device.id===authInfo?.credentialId?'Será necessário parear novamente para acessar o agent.':`${device.name} perderá acesso imediatamente.`,[{text:'Cancelar',style:'cancel'},{text:'Revogar',style:'destructive',onPress:()=>void(async()=>{setRevoking(device.id);try{const response=await fetch(normalizeAgentURL(profile,`/devices/${device.id}`),{method:'DELETE',headers:authenticatedHeaders(profile)});if(!response.ok)throw new Error();if(device.id===authInfo?.credentialId){await onSelfRevoked();return}await load()}catch{setError('Não foi possível revogar o dispositivo.')}finally{setRevoking(null)}})()}]);
  return <View style={[styles.root,{backgroundColor:theme.colors.bg}]}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={onBack} accessibilityRole="button" style={styles.back}><Icon name="chevron-back" size={18} color={theme.colors.primary}/><Text style={[styles.backText,{color:theme.colors.primary}]}>Diagnóstico</Text></Pressable><ScreenHeading title="Dispositivos" description="Credenciais com acesso ao agent deste Mac. Revogar não altera suas contas Codex ou Claude." theme={theme}/>
  {authInfo?.migrationRequired&&<View style={styles.migration}><InfoBanner title="Este perfil ainda usa o token antigo" body="Faça um novo pareamento para isolar o acesso deste aparelho." tone="warning" theme={theme}/><View style={styles.migrationAction}><ActionButton label="Migrar por QR Code" icon="qr-code-outline" theme={theme} variant="primary" onPress={onPair}/></View></View>}
  <View style={styles.heading}><Text style={[styles.section,{color:theme.colors.ink}]}>Pareados</Text><Pressable onPress={()=>void load()} disabled={loading} accessibilityRole="button"><Text style={[styles.refresh,{color:theme.colors.primary}]}>Atualizar</Text></Pressable></View>
  {loading?<View style={styles.loading}><ActivityIndicator color={theme.colors.primary}/><Text style={[styles.detail,{color:theme.colors.muted}]}>Consultando o agent…</Text></View>:error?<Text accessibilityRole="alert" style={[styles.error,{color:theme.colors.error}]}>{error}</Text>:devices.length===0?<Text style={[styles.empty,{color:theme.colors.muted}]}>Nenhum token individual ainda. O perfil atual pode ser o token mestre legado.</Text>:devices.map(device=><View key={device.id} style={[styles.row,{borderBottomColor:theme.colors.line}]}><View style={styles.copy}><View style={styles.nameLine}><Text style={[styles.name,{color:theme.colors.ink}]}>{device.name}</Text>{device.id===authInfo?.credentialId&&<Text style={[styles.current,{color:theme.colors.primary}]}>Este iPhone</Text>}</View><Text style={[styles.detail,{color:theme.colors.muted}]}>Pareado {formatRelative(device.createdAt)} · visto {device.lastSeen?formatRelative(device.lastSeen):'ainda não'}</Text><Text selectable style={[styles.id,{color:theme.colors.muted}]}>{device.id}</Text></View><Pressable onPress={()=>revoke(device)} disabled={revoking===device.id} accessibilityRole="button" accessibilityLabel={`Revogar ${device.name}`} style={styles.revoke}>{revoking===device.id?<ActivityIndicator size="small" color={theme.colors.error}/>:<Text style={[styles.revokeText,{color:theme.colors.error}]}>Revogar</Text>}</Pressable></View>)}
  <View style={styles.add}><ActionButton label="Parear outro dispositivo" icon="add-circle-outline" theme={theme} onPress={onPair}/></View></ScrollView></View>
}
const styles=StyleSheet.create({root:{flex:1},content:{paddingHorizontal:20,paddingTop:12,paddingBottom:40,maxWidth:680,width:'100%',alignSelf:'center'},back:{minHeight:44,flexDirection:'row',gap:4,alignItems:'center',alignSelf:'flex-start'},backText:{fontSize:15,fontWeight:'600'},migration:{marginTop:20},migrationAction:{marginTop:10},detail:{fontSize:12,lineHeight:17,marginTop:3},heading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:26,marginBottom:4},section:{fontSize:17,fontWeight:'700'},refresh:{fontSize:14,fontWeight:'600'},loading:{minHeight:90,alignItems:'center',justifyContent:'center',gap:8},error:{fontSize:14,lineHeight:20,paddingVertical:18},empty:{fontSize:14,lineHeight:20,paddingVertical:18},row:{minHeight:82,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:'row',alignItems:'center',paddingVertical:12,gap:12},copy:{flex:1},nameLine:{flexDirection:'row',alignItems:'center',gap:8},name:{fontSize:15,fontWeight:'600'},current:{fontSize:11,fontWeight:'700'},id:{fontSize:11,marginTop:3},revoke:{minWidth:64,minHeight:44,alignItems:'flex-end',justifyContent:'center'},revokeText:{fontSize:13,fontWeight:'600'},add:{marginTop:24}});
