import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { NotificationPreferences } from '../types';
import { Theme } from '../theme';
import { ActionButton, ScreenHeading, SectionHeading } from './ui';

export function NotificationSettingsScreen({value,supported,permission,theme,onChange,onTest}:{value:NotificationPreferences;supported:boolean;permission:string;theme:Theme;onChange:(v:NotificationPreferences)=>Promise<void>;onTest:()=>Promise<boolean>}) {
  const toggleThreshold=(n:number)=>{const thresholds=value.thresholds.includes(n)?value.thresholds.filter(x=>x!==n):[...value.thresholds,n].sort((a,b)=>a-b);void onChange({...value,thresholds})};
  return <View style={[styles.root,{backgroundColor:theme.colors.bg}]}><ScrollView contentContainerStyle={styles.content}>
    <ScreenHeading title="Alertas" description="Avisos locais e privados para acompanhar seus limites sem manter o app aberto." theme={theme}/>
    <View style={[styles.master,{backgroundColor:theme.colors.surface}]}><Row label="Ativar notificações" detail={!supported?'Requer uma nova compilação do app':permission==='denied'?'Permissão negada nos ajustes do sistema':'Solicita permissão somente ao ativar'} value={value.enabled} disabled={!supported} theme={theme} onChange={enabled=>void onChange({...value,enabled})} featured/></View>
    <SectionHeading theme={theme}>Limites de uso</SectionHeading>{[50,75,90].map(n=><Row key={n} label={`${n}% usado`} value={value.thresholds.includes(n)} disabled={!value.enabled} theme={theme} onChange={()=>toggleThreshold(n)}/>) }
    <SectionHeading theme={theme}>Janelas</SectionHeading><Row label="Janela de 5 horas" value={value.fiveHourAlerts} disabled={!value.enabled} theme={theme} onChange={fiveHourAlerts=>void onChange({...value,fiveHourAlerts})}/><Row label="Janela semanal" value={value.weeklyAlerts} disabled={!value.enabled} theme={theme} onChange={weeklyAlerts=>void onChange({...value,weeklyAlerts})}/><Row label="Previsão de esgotamento" detail="Avisa quando o ritmo recente indica fim em até 12 horas" value={value.predictiveAlerts} disabled={!value.enabled} theme={theme} onChange={predictiveAlerts=>void onChange({...value,predictiveAlerts})}/>
    <SectionHeading theme={theme}>Estado</SectionHeading><Row label="Provider indisponível" value={value.providerUnavailable} disabled={!value.enabled} theme={theme} onChange={providerUnavailable=>void onChange({...value,providerUnavailable})}/><Row label="Dados antigos" detail="Mais de 15 minutos sem leitura real" value={value.staleData} disabled={!value.enabled} theme={theme} onChange={staleData=>void onChange({...value,staleData})}/><Row label="Renovação da janela" detail="Agendada localmente para funcionar em background" value={value.windowReset} disabled={!value.enabled} theme={theme} onChange={windowReset=>void onChange({...value,windowReset})}/>
    <SectionHeading theme={theme}>Silêncio</SectionHeading><Row label="Não perturbar" detail={`Das ${String(value.quietStartHour).padStart(2,'0')}:00 às ${String(value.quietEndHour).padStart(2,'0')}:00`} value={value.quietHours} disabled={!value.enabled} theme={theme} onChange={quietHours=>void onChange({...value,quietHours})}/>{value.quietHours&&<View style={styles.hours}><HourControl label="Início" hour={value.quietStartHour} disabled={!value.enabled} theme={theme} onChange={quietStartHour=>void onChange({...value,quietStartHour})}/><HourControl label="Fim" hour={value.quietEndHour} disabled={!value.enabled} theme={theme} onChange={quietEndHour=>void onChange({...value,quietEndHour})}/></View>}
    <View style={styles.test}><ActionButton label="Testar notificação" icon="notifications-outline" theme={theme} disabled={!supported} onPress={()=>void onTest()}/></View><Text style={[styles.note,{color:theme.colors.muted}]}>O teste simula Codex em 75%, sem alterar dados ou consumir tokens.</Text>
  </ScrollView></View>;
}

function Row({label,detail,value,disabled,theme,onChange,featured=false}:{label:string;detail?:string;value:boolean;disabled?:boolean;theme:Theme;onChange:(v:boolean)=>void;featured?:boolean}) {
  return <View style={[styles.row,featured&&styles.featured,{borderBottomColor:theme.colors.line,opacity:disabled?.5:1}]}><View style={styles.copy}><Text style={[styles.label,featured&&styles.featuredLabel,{color:theme.colors.ink}]}>{label}</Text>{detail&&<Text style={[styles.detail,{color:theme.colors.muted}]}>{detail}</Text>}</View><Switch value={value} disabled={disabled} onValueChange={onChange} trackColor={{false:theme.colors.line,true:theme.colors.primary}} accessibilityLabel={label}/></View>;
}
function HourControl({label,hour,disabled,theme,onChange}:{label:string;hour:number;disabled:boolean;theme:Theme;onChange:(hour:number)=>void}) {return <View style={styles.hourControl}><Text style={[styles.hourLabel,{color:theme.colors.muted}]}>{label}</Text><View style={[styles.stepper,{backgroundColor:theme.colors.surface}]}><Pressable disabled={disabled} onPress={()=>onChange((hour+23)%24)} accessibilityRole="button" accessibilityLabel={`Diminuir hora de ${label}`} style={styles.stepButton}><Text style={[styles.stepText,{color:theme.colors.ink}]}>−</Text></Pressable><Text accessibilityLabel={`${label} ${hour} horas`} style={[styles.hourValue,{color:theme.colors.ink}]}>{String(hour).padStart(2,'0')}:00</Text><Pressable disabled={disabled} onPress={()=>onChange((hour+1)%24)} accessibilityRole="button" accessibilityLabel={`Aumentar hora de ${label}`} style={styles.stepButton}><Text style={[styles.stepText,{color:theme.colors.ink}]}>+</Text></Pressable></View></View>}

const styles=StyleSheet.create({root:{flex:1},content:{paddingHorizontal:20,paddingTop:22,paddingBottom:40,maxWidth:680,width:'100%',alignSelf:'center'},master:{borderRadius:12,paddingHorizontal:14,marginTop:22},row:{minHeight:60,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:'row',alignItems:'center',gap:12},featured:{borderBottomWidth:0,minHeight:76},featuredLabel:{fontSize:16},copy:{flex:1},label:{fontSize:14,fontWeight:'600'},detail:{fontSize:12,lineHeight:17,marginTop:2},hours:{flexDirection:'row',gap:12,marginTop:12},hourControl:{flex:1},hourLabel:{fontSize:12,fontWeight:'600',marginBottom:6},stepper:{height:44,borderRadius:10,flexDirection:'row',alignItems:'center'},stepButton:{width:44,height:44,alignItems:'center',justifyContent:'center'},stepText:{fontSize:20},hourValue:{flex:1,textAlign:'center',fontSize:14,fontWeight:'600',fontVariant:['tabular-nums']},test:{marginTop:26},note:{fontSize:12,lineHeight:18,marginTop:10,textAlign:'center'}});
