import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ConnectionProfile, DiscoveredDevice } from '../types';
import { DiscoveryState } from '../useDeviceDiscovery';
import { Theme } from '../theme';
import { validateProfile } from '../utils';
import { ActionButton, Icon, InfoBanner, ScreenHeading, SectionHeading } from './ui';

export function SetupScreen({ initial, pairedDevice, discovery, theme, onSave, onScan, onCancel }: {initial:ConnectionProfile|null;pairedDevice?:string|null;discovery:{devices:DiscoveredDevice[];state:DiscoveryState};theme:Theme;onSave:(p:ConnectionProfile)=>Promise<void>;onScan:()=>void;onCancel?:()=>void}) {
  const [profile,setProfile]=useState<ConnectionProfile>(initial??{mode:'local',endpoint:'',token:'',refreshIntervalMs:60_000});const[error,setError]=useState<string|null>(null);const[saving,setSaving]=useState(false);const[manual,setManual]=useState(Boolean(initial));
  const submit=async()=>{const nextError=validateProfile(profile);setError(nextError);if(nextError)return;setSaving(true);try{await onSave({...profile,endpoint:profile.endpoint.trim(),token:profile.token.trim()})}catch{setError('Não foi possível proteger a configuração neste aparelho.')}finally{setSaving(false)}};
  return <KeyboardAvoidingView style={[styles.root,{backgroundColor:theme.colors.bg}]} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>
    <ScreenHeading title={initial?'Conexão':'Conecte seu Mac'} description="Leia o QR do agent para criar uma conexão protegida em poucos segundos." theme={theme}/>
    <Pressable onPress={onScan} style={({pressed})=>[styles.scan,{backgroundColor:pressed?theme.colors.primaryInk:theme.colors.primary}]} accessibilityRole="button"><View style={[styles.scanIcon,{backgroundColor:theme.colors.primaryInk}]}><Icon name="qr-code-outline" size={25} color={theme.colors.onAccent}/></View><View style={styles.scanCopy}><Text style={[styles.scanTitle,{color:theme.colors.onAccent}]}>Escanear QR do Mac</Text><Text style={[styles.scanBody,{color:theme.colors.onAccent}]}>No Terminal: ./usage-agent pair</Text></View><Icon name="chevron-forward" size={20} color={theme.colors.onAccent}/></Pressable>
    {pairedDevice&&<View style={styles.feedback}><InfoBanner title="QR reconhecido" body={`${pairedDevice} · confirme abaixo para conectar.`} tone="accent" theme={theme}/></View>}
    {discovery.state!=='unsupported'&&<View style={styles.discovery}><SectionHeading theme={theme}>Macs encontrados</SectionHeading>{discovery.devices.length?discovery.devices.map(device=><Pressable key={device.id} onPress={()=>{setProfile({...profile,mode:'local',endpoint:device.endpoint,deviceId:device.id,deviceName:device.name});setManual(true)}} accessibilityRole="button" style={({pressed})=>[styles.device,{backgroundColor:pressed?theme.colors.surfacePressed:theme.colors.surface}]}><View style={[styles.deviceIcon,{backgroundColor:theme.colors.primarySoft}]}><Icon name="desktop-outline" size={20} color={theme.colors.primary}/></View><View style={styles.deviceCopy}><Text style={[styles.deviceName,{color:theme.colors.ink}]}>{device.name}</Text><Text style={[styles.deviceAddress,{color:theme.colors.muted}]}>{device.endpoint}</Text></View><Text style={[styles.useDevice,{color:theme.colors.primary}]}>Usar</Text></Pressable>):<Text style={[styles.discoveryEmpty,{color:theme.colors.muted}]}>{discovery.state==='error'?'Não foi possível procurar na rede local.':'Procurando na rede local…'}</Text>}</View>}
    {discovery.state==='unsupported'&&<Text style={[styles.nativeNote,{color:theme.colors.muted}]}>Descoberta automática disponível no development build. No Expo Go, use o QR.</Text>}
    {!manual&&<ActionButton label="Configurar manualmente" icon="options-outline" theme={theme} variant="quiet" onPress={()=>setManual(true)}/>} 
    {manual&&<View style={styles.manual}><SectionHeading theme={theme}>Configuração manual</SectionHeading>
    <View style={[styles.segment,{backgroundColor:theme.colors.surface}]}>{(['local','remote'] as const).map(mode=><Pressable key={mode} onPress={()=>setProfile({...profile,mode})} style={[styles.segmentButton,profile.mode===mode&&{backgroundColor:theme.colors.input}]} accessibilityRole="button"><Text style={{color:profile.mode===mode?theme.colors.ink:theme.colors.muted,fontWeight:'600'}}>{mode==='local'?'Wi‑Fi local':'Remoto'}</Text></Pressable>)}</View>
    <Text style={[styles.label,{color:theme.colors.ink}]}>Endereço</Text><TextInput value={profile.endpoint} onChangeText={endpoint=>setProfile({...profile,endpoint})} placeholder={profile.mode==='local'?'192.168.1.20:9876':'https://seu-tunel.ngrok.app'} placeholderTextColor={theme.colors.muted} autoCapitalize="none" autoCorrect={false} keyboardType="url" style={[styles.input,{backgroundColor:theme.colors.input,borderColor:error&&!profile.endpoint?theme.colors.error:theme.colors.line,color:theme.colors.ink}]} accessibilityLabel="Endereço do agent"/>
    <Text style={[styles.label,{color:theme.colors.ink}]}>Token</Text><TextInput value={profile.token} onChangeText={token=>setProfile({...profile,token})} placeholder="Token do agent" placeholderTextColor={theme.colors.muted} autoCapitalize="none" autoCorrect={false} secureTextEntry style={[styles.input,{backgroundColor:theme.colors.input,borderColor:error&&!profile.token?theme.colors.error:theme.colors.line,color:theme.colors.ink}]} accessibilityLabel="Token do agent"/>
    <Text style={[styles.label,{color:theme.colors.ink}]}>Atualização ativa</Text>
    <View style={[styles.interval,{backgroundColor:theme.colors.surface}]}>{([{value:30_000,label:'30 s'},{value:60_000,label:'1 min'},{value:300_000,label:'5 min'}] as const).map(option=><Pressable key={option.value} onPress={()=>setProfile({...profile,refreshIntervalMs:option.value})} style={[styles.intervalButton,(profile.refreshIntervalMs??60_000)===option.value&&{backgroundColor:theme.colors.input}]} accessibilityRole="radio" accessibilityState={{checked:(profile.refreshIntervalMs??60_000)===option.value}}><Text style={{color:(profile.refreshIntervalMs??60_000)===option.value?theme.colors.ink:theme.colors.muted,fontWeight:'600'}}>{option.label}</Text></Pressable>)}</View>
    <Text style={[styles.intervalHelp,{color:theme.colors.muted}]}>O app solicita uma leitura real dos dois providers nesse intervalo.</Text></View>}
    {error&&<Text accessibilityRole="alert" style={[styles.error,{color:theme.colors.error}]}>{error}</Text>}
    <Text style={[styles.security,{color:theme.colors.muted}]}>O token fica criptografado no SecureStore deste aparelho.</Text>
    <ActionButton label={saving?'Salvando…':'Salvar e conectar'} icon="lock-closed-outline" theme={theme} variant="primary" disabled={saving} loading={saving} onPress={()=>void submit()}/>
    {onCancel&&<Pressable onPress={onCancel} style={styles.cancel} accessibilityRole="button"><Text style={[styles.cancelText,{color:theme.colors.muted}]}>Cancelar</Text></Pressable>}
  </ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({root:{flex:1},content:{paddingHorizontal:24,paddingTop:48,paddingBottom:40,maxWidth:560,width:'100%',alignSelf:'center'},scan:{minHeight:82,borderRadius:12,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:12,marginTop:24},scanIcon:{width:48,height:48,borderRadius:10,alignItems:'center',justifyContent:'center'},scanCopy:{flex:1},scanTitle:{fontSize:16,fontWeight:'700'},scanBody:{fontSize:13,marginTop:4,opacity:.88},feedback:{marginTop:12},discovery:{marginBottom:16},device:{minHeight:64,borderRadius:12,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:12},deviceIcon:{width:40,height:40,borderRadius:10,alignItems:'center',justifyContent:'center'},deviceCopy:{flex:1},deviceName:{fontSize:14,fontWeight:'700'},deviceAddress:{fontSize:12,marginTop:2},useDevice:{fontSize:14,fontWeight:'700'},discoveryEmpty:{fontSize:13,paddingVertical:10},nativeNote:{fontSize:12,lineHeight:17,marginTop:12,marginBottom:18},manual:{marginBottom:6},segment:{padding:4,borderRadius:12,flexDirection:'row',marginBottom:24},segmentButton:{flex:1,minHeight:44,borderRadius:8,alignItems:'center',justifyContent:'center'},label:{fontSize:14,fontWeight:'600',marginBottom:8},input:{minHeight:52,borderWidth:1,borderRadius:10,paddingHorizontal:14,paddingVertical:12,fontSize:16,marginBottom:18},interval:{padding:4,borderRadius:12,flexDirection:'row'},intervalButton:{flex:1,minHeight:44,borderRadius:8,alignItems:'center',justifyContent:'center'},intervalHelp:{fontSize:12,lineHeight:17,marginTop:8,marginBottom:18},error:{fontSize:14,marginTop:-6,marginBottom:12},security:{fontSize:13,lineHeight:18,marginBottom:22},cancel:{minHeight:48,alignItems:'center',justifyContent:'center',marginTop:8},cancelText:{fontSize:15,fontWeight:'600'}});
